from collections.abc import Iterator

__all__ = ['gcd', 'lcm', 'coprime', 'iSqrt', 'isSqr', 'is_prime', 'legendre_symbol', 'jacobi_symbol', 'primes', 'primes_capped', 'primes_wilson']

def gcd(m: int, n: int, /) -> int: ...
def lcm(m: int, n: int, /) -> int: ...
def coprime(m: int, n: int, /) -> tuple[int, int]: ...
def iSqrt(n: int, /) -> int: ...
def isSqr(n: int, /) -> bool: ...
def legendre_symbol(a: int, p: int) -> int: ...
def jacobi_symbol(a: int, n: int) -> int: ...
def primes_wilson(start: int = 2) -> Iterator[int]: ...
def primes_capped(start: int, end: int) -> Iterator[int]: ...
def primes(start: int = 2, end: int | None = None) -> Iterator[int]: ...
def is_prime(n: int, /) -> bool: ...
